export const categories = [
  { value: "", label: "All Categories" },
  { value: "9", label: "General Knowlege" },
  { value: "10", label: "Books" },
  { value: "17", label: "Science & Nature" },
  { value: "18", label: "Science & Computers" },
  { value: "19", label: "Mathematics" },
  { value: "20", label: "Mythology" },
  { value: "21", label: "Sports" },
  { value: "22", label: "Geography" },
  { value: "23", label: "History" },
  { value: "24", label: "Politics" },
  { value: "25", label: "Art" },
  { value: "28", label: "Vehicles" },
];
